### ISSUE TITLE
Borderless (Duality) missing from this list??

### ISSUE THREAD

**Issue by BanaKori** [ff-meli/OrchestrionPlugin#14]
I noticed that Borderless (Duality) and Unbending Steel (Duality) from the Duality album are missing here, while Unbreakable (Duality) is in the list.

Was just wondering if there is anything preventing them from being added, or if they just haven't gotten around to it.

**Comment by ff-meli** [comment]
I don't know if these are the correct versions of those tracks, but I found these in the sheet:
* 319 - Borderless
* 325 - Unbending Steel

Neither is tagged with Duality, but that might just be an inconsistency on the part of the sheet maintainers.  If those are the correct versions, you should go to [the source sheet](https://docs.google.com/spreadsheets/d/14yjTMHYmuB1m5-aJO8CkMferRT9sNzgasYq02oJENWs/edit#gid=0) and add a comment on those tracks so they can get updated.  If they're the wrong versions, it may be that the other versions are not present in game directly.
