### ISSUE TITLE
Allow adjustment of character select screen music 

### ISSUE THREAD

**Issue by Zebouski** [ff-meli/OrchestrionPlugin#29]
With /porch, I tried to replace 4 - Prelude - Discoveries with another track, since I was a bit tired of that music from a month of long login queues, but I found it didn't work.

Would it be in scope to add support for letting track 4 on the character menu, be replaced successfully? Or would you say no and that it be more in scope for another plugin like TitleEdit as that one manages the screen just before.

**Comment by slotthhy** [comment]
Please note that this repository for the plugin is not being maintained, and this issues page is not monitored. Issues should be brought up here: https://github.com/lmcintyre/OrchestrionPlugin

I do think something like this is more intended for Title Edit. The BGM system that handles the title screen theme is not the same BGM system that plays music when in-game, so Orchestrion cannot control it and it would require more research to implement, for something that another plugin already handles.

**Comment by Zebouski** [comment]
thanks, I was looking for upstream and thought this was it.

I'll hit up titleedit instead.
